// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTask struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	UserID  string `json:"userId"`
}

type CreateUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Task struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
	UserID  string `json:"userId"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
