CREATE DATABASE IF NOT EXISTS go_todo;

USE go_todo;

CREATE TABLE IF NOT EXISTS users(
    id varchar(36) PRIMARY KEY NOT NULL,
    name VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(254) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks(
    id varchar(36) PRIMARY KEY NOT NULL,
    title VARCHAR(50) NOT NULL,
    content VARCHAR(140) NOT NULL,
    user_id varchar(36) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);
